export enum GameState {
  BOOT = 'BOOT',
  MAIN_MENU = 'MAIN_MENU',
  LOADING = 'LOADING',
  PLAYING = 'PLAYING',
  ROUND_START = 'ROUND_START',
  ROUND_ACTIVE = 'ROUND_ACTIVE',
  ROUND_COMPLETE = 'ROUND_COMPLETE',
  PAUSED = 'PAUSED',
  GAME_OVER = 'GAME_OVER',
}
